/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Laurie' at '15/07/16 17:52' with Gradle 2.14
 *
 * @author Laurie, @date 15/07/16 17:52
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
